sudo: required
language: python

python:
  - "2.7"
  - "3.6"

env:
  - TOXENV=py36,codecov
  # - TOXENV=py27

# matrix:
#   exclude:
#     - python: "3.6"
#       env: TOXENV=py27
#     - python: "2.7"
#       env: TOXENV=py36,codecov

install:
  - pip install tox

script:
  - tox

notifications:
  email: false
